name: CI

on:
  push:

jobs:
  build-development-image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: set docker env variables
        run: |
          echo ::set-env name=DOCKER_USERNAME::"AWS"
          echo ::set-env name=DOCKER_PASSWORD::$(aws ecr get-login-password)
      - uses: docker/build-push-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          registry: "730058107677.dkr.ecr.ap-south-1.amazonaws.com"
          repository: "bitfex/frontend"
          tags: alpha5-userdashboard,alpha5-userdashboard-${{ github.sha }}
  deploy-development:
    runs-on: ubuntu-latest
    needs: build-development-image
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: "Update deployment image"
        uses: Eyevinn/action-eks-kubectl@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ap-south-1
          CLUSTER: bitfex-development
        with:
          args: set image --record deployment/alpha5-userdashboard alpha5-userdashboard=730058107677.dkr.ecr.ap-south-1.amazonaws.com/bitfex/frontend:alpha5-userdashboard-${{ github.sha }}
      - name: "Check rollout status"
        uses: Eyevinn/action-eks-kubectl@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ap-south-1
          CLUSTER: bitfex-development
        with:
          args: '"rollout status deployment/alpha5-userdashboard"'
